name: Topology

on:
  schedule:
  - cron: "0 16 * * *"

  workflow_dispatch:

jobs:
  topology:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Install GraphViz
        run: sudo apt install graphviz -y

      - uses: actions/checkout@v3

      - name: Generate Topology
        run: ./export.sh

      - uses: stefanzweifel/git-auto-commit-action@v4

